### ISSUE TITLE
Create PageNotFound Component

### ISSUE THREAD

**Issue by Wolven531** [Wolven531/simple-cra-app#10]
Rather than have our Page not found declared in the render for App (in `src/App/App.tsx`), we should make a separate component for it; this way, App stays cleaner and we can elaborate and iterate on the Not Found page w/o risking anything in App

**Comment by centanomics** [comment]
Hi, wondering if I can be approved as a contributor so I can work on this issue. Thanks!

**Comment by Wolven531** [comment]
@centanomics - definitely; inviting you now and re-assigning this 😀

**Comment by Wolven531** [comment]
There some interesting examples here - https://uicookies.com/500-error-page-templates

We don't have an explicit theme or style yet, so artistic license is all yours =]

**Comment by Wolven531** [comment]
Note that @VincentLeighton is working on a first pass of this (in the linked PR); your changes can build off of that, @centanomics =]
