### ISSUE TITLE
Create HomePage component

### ISSUE THREAD

**Issue by Wolven531** [Wolven531/simple-cra-app#21]
Rather than have our Home Page declared in the render for App (in `src/App/App.tsx`), we should make a separate component for it; this way, App stays cleaner and we can elaborate and iterate on the Home Page w/o risking anything in App

This issue (https://github.com/Wolven531/simple-cra-app/issues/10) has an example of how this was done for the PageNotFoundPage; the PR that closed it is here - https://github.com/Wolven531/simple-cra-app/pull/12

**Comment by cod500** [comment]
Can I help out on this issue?
