### ISSUE TITLE
Add e2e tests (Cypress) to confirm new Nav works (and avoid regressions)

### ISSUE THREAD

**Issue by Wolven531** [Wolven531/simple-cra-app#33]

**Comment by jhechtf** [comment]
I've never been able to get Cypress to work personally, but I work quite frequently with [TestCafe](https://testcafe.io/) quite a lot.

**Comment by Roughnick** [comment]
Really? But Cypress is easy to install and run.

**Comment by jhechtf** [comment]
I don't personally care; my only issue is that up until recently I've had issues with Cypress running correctly for me, whereas I've always been able to get TestCafe going. Since we have it setup for Cypress already then that's fine but I'll be less knowledgeable about that.
