### ISSUE TITLE
User search needs a spinner

### ISSUE THREAD

**Issue by Roughnick** [Wolven531/simple-cra-app#35]
As a user, I would like to know the application is processing my request when I click search from the **Search User** page.

**Comment by Wolven531** [comment]
Verified this works in staging -

![image](https://user-images.githubusercontent.com/2125913/124845342-c7112000-df53-11eb-9547-567fe7574597.png)

![image](https://user-images.githubusercontent.com/2125913/124845349-cb3d3d80-df53-11eb-851f-0669a467e460.png)
