### ISSUE TITLE
Convert SearchUsersPage to Component class

### ISSUE THREAD

**Issue by Wolven531** [Wolven531/simple-cra-app#37]
The code is complex enough, we should convert the Functional Component (FC) to a full class (that extends React.Component and implements `render()`)

**Comment by jhechtf** [comment]
How is that supposed to make the code any easier to read?

**Comment by Wolven531** [comment]
It's not; after some further consideration, we're going to aim to use FC as much as possible. With a little utility function help, we can get a fairly smooth testing flow going; The ConfigPage currently uses jest and RTL pretty smoothly (since #41 ), so I'm going to close this issue
