### ISSUE TITLE
User search - Unexpected end of JSON input

### ISSUE THREAD

**Issue by Roughnick** [Wolven531/simple-cra-app#43]
When you enter a username, that doesn't exist, an error message appears that states "Unexpected end of JSON input". Is this expected? Could we add a more user friendly message?

Username = sdgfdsge45

![2021-07-06_22h00_20](https://user-images.githubusercontent.com/3384059/124699110-67f5d180-dea7-11eb-85af-fa6a112343b2.png)

**Comment by Wolven531** [comment]
Currently it is expected, and we definitely SHOULD add a better UX xD

I'll take a look at this

**Comment by Wolven531** [comment]
Also, w/ @VincentLeighton 's new spinner in place, it looks like really large screen resolutions treat the modal weird - 

![image](https://user-images.githubusercontent.com/2125913/124845463-06d80780-df54-11eb-84cd-90b3afc47222.png)

I'll see if I can address that w/ this ticket as well

**Comment by Wolven531** [comment]
How's this look? @Roughnick and @VincentLeighton ?

![image](https://user-images.githubusercontent.com/2125913/125145917-b93cd580-e0e0-11eb-80af-405652d92d11.png)
