### ISSUE TITLE
Add button on SearchUsersPage to add user to server's list of users

### ISSUE THREAD

**Issue by Wolven531** [Wolven531/simple-cra-app#54]
After a successful lookup, a user should be able to click a button on the SearchUsersPage to add themselves to the server's list of users. After this, the user should find be able to find themselves on the "All Users" page

API info - https://simple-nest-staging.herokuapp.com/#/user/UserController_addUser

**Comment by VincentLeighton** [comment]
I don't see an API endpoint for saving the new user, it doesn't make sense to me to save this list locally. How do we proceed from here?
