### ISSUE TITLE
BUG - Page breaks when comparing users

### ISSUE THREAD

**Issue by Wolven531** [Wolven531/simple-cra-app#73]
Steps to reproduce -

prod env -

1. Visit compare users page - https://simple-cra-prod.herokuapp.com/compare
2. ![image](https://user-images.githubusercontent.com/2125913/150069842-e62079e9-7156-46a0-bce2-beb6d01773f5.png)
3. Select second user
4. ![image](https://user-images.githubusercontent.com/2125913/150069906-2ee84013-5464-4fbd-b759-b4d4ef3151a8.png)
5. Click search button
6. ![image](https://user-images.githubusercontent.com/2125913/150069980-54bc9de6-6ad5-4642-970f-135dcabcb1b5.png)
7. Error occurs

![image](https://user-images.githubusercontent.com/2125913/150070055-fce5dd3b-8515-4904-9661-e3e222f41142.png)

![image](https://user-images.githubusercontent.com/2125913/150070141-9f06add8-4ae8-411b-ba8b-ac70fb50964f.png)

**Comment by VincentLeighton** [comment]
Works as intended, does not crash.
